name: GitHub Workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    uses: BrunoBrasolin/workflow-template/.github/workflows/angular-docker-ci.yml@main
    with:
      image: brunobrasolin/front-bills-calculate-percentage
    secrets: inherit
